### ISSUE TITLE
Fuel tank selector missing

### ISSUE THREAD

**Issue by davidmegginson** [TheFGFSEagle/c140#2]
The Cessna 140 did not have a "Both" setting for fuel (unlike later Cessnas) so it draws from only one tank at a time and quickly gets out of balance and/or runs out of fuel. The only way to switch tanks is to open the Properties tree and dig down, which isn't practical for most FlightGear users.

In the short term, we could add something in the Aircraft menu as a quick fix (that might be more practical for many users anyway).

In the medium term, we should add the fuel selector as a usable 3D model.

From the [Operation Manual for Cessna 120/140](https://ad7zj.net/wiki/images/1/19/Operation_Manual_for_Cessna_120_140.pdf)

![image](https://github.com/TheFGFSEagle/c140/assets/2810060/cd92e0db-bd18-4311-b7e6-02238a1998a9)

**Comment by davidmegginson** [comment]
(The photo is sideways; it's on the floor beside the base of the flap handle.)

**Comment by magnetic-eagle** [comment]
Added, and seems to be working - test results welcome ! :)
